### ISSUE TITLE
Example: Error in cons != .consold : non-conformable arrays

### ISSUE THREAD

**Issue by durrantmm** [renozao/NMF#133]
Hello everyone,

I know this is a common issue. I installed the `devel` version, and it was not resolved.

I tried running NMF on the provided matrix with the command:

`nmf(mat, 4, 'brunet', seed=123456)`

And I get the error

```
Error in cons != .consold : non-conformable arrays
Timing stopped at: 0.855 0.002 0.858
```

I have also tried removing columns with a lot of missing data, but it doesn't resolve the issue.

Any advice?
[final_nmf_matrix.dat.txt](https://github.com/renozao/NMF/files/2965003/final_nmf_matrix.dat.txt)

**Comment by renozao** [comment]
Your data has columns that are all zeros or have missing values, this is not supported.
If you do the following you should be good:
```R
mat <- read.delim("https://github.com/renozao/NMF/files/2965003/final_nmf_matrix.dat.txt", header = FALSE)
# convert into a matrix
mat <- as.matrix(mat)
i0 <- which(colSums(mat) == 0)
i_na <- which(colSums(is.na(mat)) > 0)
res <- nmf(mat[, -c(i0, i_na)], 4, 'brunet', seed=123456)
```

I have just pushed another fix (unrelated to this issue), so you may want to re-install the `devel` branch.

**Comment by renozao** [comment]
@durrantmm did that fix your issue?

**Comment by grenaud** [comment]
I had the same issue and it worked, thank you!

**Comment by Donatella93** [comment]
Hi!
I got the same issue,
I am trying to fix it by using the code from renozao 
but I still get the error 

> res <- nmf(data[, -c(i0, i_na)], 4, 'brunet', seed=123456)
Error in cons != .consold : non-conformable arrays
Timing stopped at: 0.01 0 0.02

**Comment by italorossidela** [comment]
Hi everyone!

I have no missing values or all-zero columns, and I am still getting the same error.

**Comment by pcantalupo** [comment]
I'm getting the same error.  None of my rows nor columns are all-zeros:

```
> table(colSums(forNMF) > 0)

TRUE 
  49 
> table(rowSums(forNMF) > 0)

TRUE 
 128 
> res <- nmf(forNMF, rank = 3, method = "brunet", .options = 'v')
NMF algorithm: 'brunet'
NMF seeding method: random
Iterations:    1/2000Error in cons != .consold : non-conformable arrays
Timing stopped at: 0.035 0.001 0.037
> 
```
