### ISSUE TITLE
maxIter error

### ISSUE THREAD

**Issue by HarlanH** [renozao/NMF#37]
Hi, I'm running 0.20.6, and am getting an error related to maxIter:

``` r
> ret <- nmf(cg_full, rank=rank, method='ls-nmf', weight=as.numeric(cg_full>0), nrun=nrun,
+            maxIter=100,
+            seed="random", 
+            .options = list(parallel=TRUE, track=TRUE, verbose=1)
+ ) 
NMF algorithm: 'ls-nmf'
NMF seeding method: random
Error in obj.fun(x, y, ...) : unused argument (maxIter = 100)
```

What could be causing this?

**Comment by HarlanH** [comment]
This definitely is limited to `ls-nmf`, which I have to use because of missing data. When I use other methods, `maxIter` seems to work.

**Comment by renozao** [comment]
I can't reproduce this on version 0.22.
Can you please install from github (master) and re-try.

You will need to update pkgmaker as well:

```
install_github('renozao/pkgmaker', ref = 'devel')
install_github('renozao/NMF')
```

**Comment by HarlanH** [comment]
Nope, those versions don't work for me either:

```r
> ret <- nmf(cg_full, rank=rank, method='ls-nmf', weight=as.numeric(cg_full>0), nrun=1,
+            maxIter=500,
+            seed="random", 
+            .options = list(parallel=FALSE, track=TRUE, verbose=1)
+ ) 
NMF algorithm: 'ls-nmf'
NMF seeding method: random
Error in obj.fun(x, y, ...) : unused argument (maxIter = 500)
```

Oddly, adding `options(error=recover)` doesn't capture this, so I can't figure out how to debug...

**Comment by renozao** [comment]
Indeed. I had overlooked argument `track`.
Should now be fixed on `devel` branch.

**Comment by HarlanH** [comment]
Ah, thank you! 

For uninteresting reasons, I have to use the CRAN version. I'll monkey patch in the interim. Is there going to be a CRAN release anytime soon?

**Comment by renozao** [comment]
No release is planned in the very near future (mainly due to time).
We can exchange by email if you think I can help with a work around for
your CRAN restriction.

Try the following, which should fix the issue on your current version:

setNMFMethod('ls-nmf', NMF:::.ls_nmf, objective=function(object, X, weight
= 1, ...) NMF:::wrss(object, X, weight), overwrite=TRUE)

**Comment by HarlanH** [comment]
Hm, for v0.20.6, that doesn't work:

```r
> setNMFMethod('ls-nmf', NMF:::.ls_nmf, 
+              objective=function(object, X, weight = 1, ...) NMF:::wrss(object, X, weight), 
+              overwrite=TRUE)
Error in NMFStrategy(name = "ls-nmf", method = NMF:::.ls_nmf, objective = function(object,  : 
  error in evaluating the argument 'method' in selecting a method for function 'NMFStrategy': Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object '.ls_nmf' not found
```
Here are the objects available:

```r
> grep("ls", unclass(lsf.str(envir = asNamespace("NMF"), all = T)), value=TRUE)
 [1] ".cssls"                          ".fcnnls"                         ".init.nmf.models"               
 [4] "fcnnls"                          "nmf_update.lsnmf"                "nmfAlgorithm.lsNMF"             
 [7] "nmfFormals"                      "nmfFormals.character"            "nmfFormals.NMFStrategy"         
[10] "nmfFormals.NMFStrategyFunction"  "nmfFormals.NMFStrategyIterative" "nmfModels"                      
[13] "print.fcnnls"                    "residuals"                       "residuals<-"                    
[16] "runit.lsnmf"    
```

**Comment by renozao** [comment]
Right. The CRAN version is quite behind the GitHub master (sigh).
Try this:

```R
setNMFMethod('ls-nmf', objective = function(object, X, weight, ...) NMF:::wrss(object, X, weight)
                         , Update=NMF:::nmf_update.lsnmf, Stop='stationary'
                         , overwrite = TRUE)
```

**Comment by HarlanH** [comment]
That works, thanks!

**Comment by JianghuiDu** [comment]
I know this is such a long time ago but this problem still happens. I'm using CRAN 0.22.0
